FROM rust:1.62.1-slim-bullseye

RUN apt-get update && apt-get install build-essential -y

WORKDIR app

COPY . .

RUN cargo build --release

EXPOSE 3000

CMD ["/app/target/release/centarr"]